import './globals.css'
import './style.css'
import type { Metadata } from 'next'
import { Inter, Roboto_Serif } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PROVEDDy',
  description: 'Generated by create next app',
  // icons propiedad para cambiar el icono a la pagina
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
